# Pandas Series

### creating Series

#### There are multiple ways to create a pandas Series:

In [2]:
import numpy as np 
import pandas as pd

In [3]:
labels = ['a','b','c']
my_lists = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [5]:
pd.Series(my_lists)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(my_lists,index = labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# dataFrame

In [ ]:
import numpy as np
import pandas as pd

### Creation a Dataframe

In [15]:
data =  {
    'Name' : ['john', 'Anna', 'peter', 'Linda'],
    'Age' : [28,34,29,42], 
    'City' : ['New York', 'Paris', 'Berlin', 'London'], 
    'Salary' : [65000,70000,62000,85000]
}
df = pd.DataFrame(data)

In [16]:
df

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
data_list = [
    ['john',28,'New York', 650000], 
    ['Anna', 34, 'paris', 70000], 
    ['peter', 29, 'Berlin', 62000], 
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [19]:
df2

       0   1         2       3
0   john  28  New York  650000
1   Anna  34     paris   70000
2  peter  29    Berlin   62000
3  Linda  42    London   85000

In [21]:
columns = ["Name",'Age',"City","Salary"]
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   john   28  New York  650000
1   Anna   34     paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
headers = ['home','area','price']
location = [
    ['titra','siwan','bihar'],
    ['Nitsh','vikash','deva'],
    [2342333,523423,42343]
]
df3 = pd.DataFrame(location,columns = headers)

In [25]:
df3

      home    area  price
0    titra   siwan  bihar
1    Nitsh  vikash   deva
2  2342333  523423  42343

### Selection and indexing of columns

In [32]:
df[['Name','Age','City']]

    Name  Age      City
0   john   28  New York
1   Anna   34     Paris
2  peter   29    Berlin
3  Linda   42    London

In [52]:
df['Designation'] = ['manager','assistant','director','clerk']
df

    Name  Age      City  Salary Designation
0   john   28  New York   65000     manager
1   Anna   34     Paris   70000   assistant
2  peter   29    Berlin   62000    director
3  Linda   42    London   85000       clerk

In [53]:
df.drop('Designation', axis = 1)
df

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

### Selecting a Row

In [54]:
df

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [55]:
df.loc[0]

Name          john
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [56]:
df.loc[[0,1,2]]

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000

In [57]:
df.iloc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

### Selecting Subsets of Rows and Columns

In [59]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

### Conditional Selection

In [60]:
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   paris   70000
3  Linda   42  London   85000

In [65]:
df[(df['Age']>30) & df['City'] == 'London']

Empty DataFrame
Columns: [Name, Age, City, Salary]
Index: []

# Missing Data

### Finding Missiong Data