# Pandas Series

### creating Series

#### There are multiple ways to create a pandas Series:

In [2]:
import numpy as np 
import pandas as pd

In [3]:
labels = ['a','b','c']
my_lists = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [5]:
pd.Series(my_lists)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(my_lists,index = labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# dataFrame

In [ ]:
import numpy as np
import pandas as pd

### Creation a Dataframe

In [15]:
data =  {
    'Name' : ['john', 'Anna', 'peter', 'Linda'],
    'Age' : [28,34,29,42], 
    'City' : ['New York', 'Paris', 'Berlin', 'London'], 
    'Salary' : [65000,70000,62000,85000]
}
df = pd.DataFrame(data)

In [16]:
df

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
data_list = [
    ['john',28,'New York', 650000], 
    ['Anna', 34, 'paris', 70000], 
    ['peter', 29, 'Berlin', 62000], 
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [19]:
df2

       0   1         2       3
0   john  28  New York  650000
1   Anna  34     paris   70000
2  peter  29    Berlin   62000
3  Linda  42    London   85000

In [21]:
columns = ["Name",'Age',"City","Salary"]
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   john   28  New York  650000
1   Anna   34     paris   70000
2  peter   29    Berlin   62000
3  Linda   42    London   85000